#!/usr/bin/env python3
"""Emit the single-byte decode tables in src/convert.rs and their expected
values for tests/encodingtest.rs.

Both halves come from Python's own codec tables, so the Rust tables cannot
drift from a well-tested reference by transcription error. The two generated
blocks are checked against each other by
`every_table_entry_matches_python`, which is the test that would catch a
regeneration mistake.

    python3 tests/gen_encoding_tables.py > /tmp/tables.rs

Nothing imports this at build or test time: the generated code is committed, so
the test suite does not require Python. Regenerate only when an encoding is
added or a table is suspected wrong, and expect the cross-check test to move
with it.
"""

# (Python codec, Rust constant suffix, canonical --encoding name)
ENCODINGS = [
    ("iso8859_1", "LATIN1", "iso-8859-1"),
    ("cp1252", "CP1252", "cp1252"),
    ("cp1251", "CP1251", "cp1251"),
    ("cp1253", "CP1253", "cp1253"),
    ("koi8_r", "KOI8R", "koi8-r"),
]


def high_half(codec: str) -> list[int | None]:
    """Code points for 0x80-0xFF, or None where the codec leaves the byte
    undefined."""
    out: list[int | None] = []
    for byte in range(0x80, 0x100):
        try:
            out.append(ord(bytes([byte]).decode(codec)))
        except UnicodeDecodeError:
            out.append(None)
    return out


def rust_tables() -> str:
    """The `static *_HIGH` blocks in src/convert.rs."""
    parts = ["// GENERATED by tests/gen_encoding_tables.py -- do not edit by hand."]
    for codec, suffix, _ in ENCODINGS:
        table = high_half(codec)
        lines = [f"static {suffix}_HIGH: [u32; 128] = ["]
        for row in range(0, 128, 8):
            cells = ["0" if v is None else f"0x{v:04x}" for v in table[row : row + 8]]
            lines.append("    " + ", ".join(cells) + ",")
        lines.append("];")
        undefined = [0x80 + i for i, v in enumerate(table) if v is None]
        if undefined:
            lines.append(
                f"// {suffix}: undefined at {', '.join('0x%02x' % b for b in undefined)}"
            )
        parts.append("\n".join(lines))
    return "\n\n".join(parts) + "\n"


def rust_expected() -> str:
    """The `EXPECTED_HIGH` cross-check block in tests/encodingtest.rs."""
    parts = [
        "// GENERATED by tests/gen_encoding_tables.py -- do not edit by hand.",
        "// The reference the hand-written tables in src/convert.rs are checked",
        "// against, byte for byte.",
        "const EXPECTED_HIGH: &[(&str, &[u32; 128])] = &[",
    ]
    for codec, _, _ in ENCODINGS:
        table = high_half(codec)
        parts.append(f'    ("{codec}", &[')
        for row in range(0, 128, 16):
            cells = ["0" if v is None else f"0x{v:04x}" for v in table[row : row + 16]]
            parts.append("        " + ", ".join(cells) + ",")
        parts.append("    ]),")
    parts.append("];")
    return "\n".join(parts) + "\n"


if __name__ == "__main__":
    import sys

    which = sys.argv[1] if len(sys.argv) > 1 else "tables"
    if which == "tables":
        print(rust_tables(), end="")
    elif which == "expected":
        print(rust_expected(), end="")
    else:
        raise SystemExit("usage: gen_encoding_tables.py [tables|expected]")